---
services:
  docs:
    image: fiafcore-docs-dev
    container_name: fiafcore-docs-dev
    restart: always
    ports:
      - "5030:5030"
    environment:
      - PORT=5030
      - INSTANCE=dev
  example:
    image: fiafcore-docs-example
    container_name: fiafcore-docs-example
    restart: always
    ports:
      - "5031:5031"
    environment:
      - PORT=5031
      - INSTANCE=example
