prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix fiaf: <https://dev.fiafcore.org/>

construct {

  SUBJECT_URI rdfs:label ?label .
  rdfs:label rdfs:label ?labelLabel .

  SUBJECT_URI rdf:type ?type .
  ?type rdfs:label ?typeLabel .

  SUBJECT_URI fiaf:hasColourCharacteristic ?colourCharacteristic .
  fiaf:hasColourCharacteristic rdfs:label ?colourCharacteristicPropLabel .
  ?colourCharacteristic rdf:type ?colourCharacteristicType .
  ?colourCharacteristicType rdfs:label ?colourCharacteristicTypeLabel .

  ?colourCharacteristic fiaf:hasColourStandard ?colourStandard .
  fiaf:hasColourStandard rdfs:label ?colourStandardPropLabel .
  ?colourStandard rdf:type ?colourStandardType .
  ?colourStandardType rdfs:label ?colourStandardTypeLabel .

  SUBJECT_URI fiaf:hasFormat ?format .
  ?format rdfs:label ?formatLabel .
  fiaf:hasFormat rdfs:label ?formatPropLabel .

  SUBJECT_URI fiaf:hasIdentifier ?identifier .
  fiaf:hasIdentifier rdfs:label ?identifierPropLabel .
  ?identifier rdf:type ?identifierType .
  ?identifierType rdfs:label ?identifierTypeLabel .
  ?identifier fiaf:hasIdentifierValue ?identifierValue .
  fiaf:hasIdentifierValue rdfs:label ?identifierValuePropLabel .
  ?identifier fiaf:hasIdentifierAuthority ?identifierAuthority .
  fiaf:hasIdentifierAuthority rdfs:label ?identifierAuthorityPropLabel .
  ?identifierAuthority rdfs:label ?identifierAuthorityLabel .

  SUBJECT_URI fiaf:hasItem ?item .
  ?item rdfs:label ?itemLabel .
  fiaf:hasItem rdfs:label ?itemPropLabel .

  SUBJECT_URI fiaf:hasLanguageUsage ?languageUsage .
  fiaf:hasLanguageUsage rdfs:label ?languageUsagePropLabel .
  ?languageUsage rdf:type ?languageUsageType .
  ?languageUsageType rdfs:label ?languageUsageTypeLabel .
  ?languageUsage fiaf:hasLanguage ?language .
  fiaf:hasLanguage rdfs:label ?languagePropLabel .
  ?language rdfs:label ?languageLabel .

  SUBJECT_URI fiaf:hasSoundCharacteristic ?soundCharacteristic .
  fiaf:hasSoundCharacteristic rdfs:label ?soundCharacteristicPropLabel .
  ?soundCharacteristic rdf:type ?soundCharacteristicType .
  ?soundCharacteristicType rdfs:label ?soundCharacteristicTypeLabel .

  ?soundCharacteristic fiaf:hasSoundStandard ?soundStandard .
  fiaf:hasSoundStandard rdfs:label ?soundStandardPropLabel .
  ?soundStandard rdf:type ?soundStandardType .
  ?soundStandardType rdfs:label ?soundStandardTypeLabel .

  SUBJECT_URI fiaf:hasTitle ?title .
  fiaf:hasTitle rdfs:label ?titlePropLabel .
  ?title rdf:type ?titleType .
  ?titleType rdfs:label ?titleTypeLabel .
  ?title fiaf:hasTitleValue ?titleValue .
  fiaf:hasTitleValue rdfs:label ?titleValuePropLabel .

}
where {
  SUBJECT_URI rdfs:label ?label .
  rdfs:label rdfs:label ?labelLabel .
  SUBJECT_URI rdf:type ?type .
  ?type rdfs:label ?typeLabel .
  optional {
    SUBJECT_URI fiaf:hasColourCharacteristic ?colourCharacteristic .
    fiaf:hasColourCharacteristic rdfs:label ?colourCharacteristicPropLabel .
    ?colourCharacteristic rdf:type ?colourCharacteristicType .
    ?colourCharacteristicType rdfs:label ?colourCharacteristicTypeLabel .
    optional{
      ?colourCharacteristic fiaf:hasColourStandard ?colourStandard .
      fiaf:hasColourStandard rdfs:label ?colourStandardPropLabel .
      ?colourStandard rdf:type ?colourStandardType .
      ?colourStandardType rdfs:label ?colourStandardTypeLabel .
    }
  }
  optional {
    SUBJECT_URI fiaf:hasFormat ?format .
    ?format rdfs:label ?formatLabel .
    fiaf:hasFormat rdfs:label ?formatPropLabel .
  }
  optional {
    SUBJECT_URI fiaf:hasIdentifier ?identifier .
    fiaf:hasIdentifier rdfs:label ?identifierPropLabel .
    ?identifier rdf:type ?identifierType .
    ?identifierType rdfs:label ?identifierTypeLabel .
    ?identifier fiaf:hasIdentifierValue ?identifierValue .
    fiaf:hasIdentifierValue rdfs:label ?identifierValuePropLabel .
    ?identifier fiaf:hasIdentifierAuthority ?identifierAuthority .
    fiaf:hasIdentifierAuthority rdfs:label ?identifierAuthorityPropLabel .
    ?identifierAuthority rdfs:label ?identifierAuthorityLabel .
  }
  optional {
    SUBJECT_URI fiaf:hasItem ?item .
    ?item rdfs:label ?itemLabel .
    fiaf:hasItem rdfs:label ?itemPropLabel .
  }
  optional {
    SUBJECT_URI fiaf:hasLanguageUsage ?languageUsage .
    fiaf:hasLanguageUsage rdfs:label ?languageUsagePropLabel .
    ?languageUsage rdf:type ?languageUsageType .
    ?languageUsageType rdfs:label ?languageUsageTypeLabel .
    ?languageUsage fiaf:hasLanguage ?language .
    fiaf:hasLanguage rdfs:label ?languagePropLabel .
    ?language rdfs:label ?languageLabel .
  }
  optional {
    SUBJECT_URI fiaf:hasSoundCharacteristic ?soundCharacteristic .
    fiaf:hasSoundCharacteristic rdfs:label ?soundCharacteristicPropLabel .
    ?soundCharacteristic rdf:type ?soundCharacteristicType .
    ?soundCharacteristicType rdfs:label ?soundCharacteristicTypeLabel .
    optional{
      ?soundCharacteristic fiaf:hasSoundStandard ?soundStandard .
      fiaf:hasSoundStandard rdfs:label ?soundStandardPropLabel .
      ?soundStandard rdf:type ?soundStandardType .
      ?soundStandardType rdfs:label ?soundStandardTypeLabel .
    }
  }
  optional {
    SUBJECT_URI fiaf:hasTitle ?title .
    fiaf:hasTitle rdfs:label ?titlePropLabel .
    ?title rdf:type ?titleType .
    ?titleType rdfs:label ?titleTypeLabel .
    ?title fiaf:hasTitleValue ?titleValue .
    fiaf:hasTitleValue rdfs:label ?titleValuePropLabel .
  }
}
