prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix fiaf: <https://dev.fiafcore.org/>

construct {

  SUBJECT_URI rdfs:label ?label .
  rdfs:label rdfs:label ?labelLabel .

  SUBJECT_URI rdf:type ?type .
  ?type rdfs:label ?typeLabel .

  SUBJECT_URI dc:description ?description .
  dc:description rdfs:label ?descriptionPropLabel .

  SUBJECT_URI dc:source ?source .
  dc:source rdfs:label ?sourcePropLabel .

  SUBJECT_URI  rdfs:domain ?domain .
  ?domain rdfs:label ?domainLabel .
  rdfs:domain rdfs:label ?domainPropLabel .

  SUBJECT_URI  rdfs:range ?range .
  ?range rdfs:label ?rangeLabel .
  rdfs:range rdfs:label ?rangePropLabel .

}
where {
  SUBJECT_URI rdfs:label ?label .
  rdfs:label rdfs:label ?labelLabel .
  SUBJECT_URI rdf:type ?type .
  ?type rdfs:label ?typeLabel .
  optional {
    SUBJECT_URI dc:description ?description .
    dc:description rdfs:label ?descriptionPropLabel .
  }
  optional {
    SUBJECT_URI dc:source ?source .
    dc:source rdfs:label ?sourcePropLabel .
  }
  optional {
    SUBJECT_URI  rdfs:domain ?domain .
    ?domain rdfs:label ?domainLabel .
    rdfs:domain rdfs:label ?domainPropLabel .
  }
  optional {
    SUBJECT_URI  rdfs:range ?range .
    ?range rdfs:label ?rangeLabel .
    rdfs:range rdfs:label ?rangePropLabel .
  }
}
